
//----------------------------------------------------------------------//
// Get selected shape as input mesh										//
//----------------------------------------------------------------------//

string $selection[] = `ls -sl`;
string $shapes[] = `listRelatives -children -shapes $selection[0]`;
string $inputMesh = $shapes[0];

//----------------------------------------------------------------------//
// Create transform/mesh/shader for output connections					//
//----------------------------------------------------------------------//

string $nodeTransform = `createNode -n StitchMeshTransform transform`;					// -n StitchMeshTransform;
string $nodeShape = `createNode mesh -n StitchMeshShape -p $nodeTransform`;		// -n StitchMeshShape1 -p StitchMeshShape;
sets -add initialShadingGroup $nodeShape;

//----------------------------------------------------------------------//
// Create stitch meshes node and connect input mesh and output mesh		//
//----------------------------------------------------------------------//

$node = `createNode StitchMeshNode -n StitchMeshNode`;
connectAttr ($inputMesh + ".outMesh") ($node + ".inputMesh");
connectAttr ($node + ".outputMesh") ($nodeShape + ".inMesh");